'use client';
import React from 'react';
import {Dices} from 'lucide-react';
import type { ActionKind,TacticalEnvironment,TacticalToken } from '@/types/tactical-map';
import { useTacticalMapStore } from '@/stores/useTacticalMapStore';
import { TacticalDialog } from './TacticalCharacterWindow';
import { CharacterAction } from './TacticalUiLogic';
import styles from './tactical-map.module.css';
export type TacticalTemplate=Pick<TacticalToken,'name'|'kind'|'hp'|'maxHp'|'initiative'|'vision'|'elevation'|'color'> & {id:string;characterId?:string};
export const SLOT_NAMES:Record<ActionKind,string>={movement:'Movimento',main:'Ação principal',bonus:'Ação bônus'};
export const ENV_NAMES:Record<string,string>={name:'Área',biome:'Bioma',temperature:'Temperatura',time:'Horário',notes:'Notas'};
export function TacticalForms({mode,onClose,onTemplate}:{mode:'create'|'scene'|'npc'|'token';onClose:()=>void;onTemplate:(template:TacticalTemplate)=>void}) {
  const {view,send,pending,selectScene,selectedTokenId,selectToken}=useTacticalMapStore();const scene=view?.scene;const token=scene?.tokens.find(t=>t.id===selectedTokenId);
  if(view?.self.role!=='admin')return null;
  const title=mode==='create'?'Criar cena de preparação':mode==='scene'?'Configurar cena':mode==='npc'?'Criar modelo manual de NPC':`Editar ${token?.name || 'token'}`;
  const submit=(event:React.FormEvent<HTMLFormElement>)=>{
    event.preventDefault();const d=new FormData(event.currentTarget);
    if(mode==='create'){void send({type:'createScene',name:String(d.get('name'))}).then(ok=>{if(ok)onClose();});return;}
    if(mode==='npc'){const hp=Number(d.get('hp'));onTemplate({id:`npc:${crypto.randomUUID()}`,name:String(d.get('name')).trim(),kind:d.get('kind')==='hostile'?'hostile':'npc',hp,maxHp:hp,initiative:Number(d.get('initiative')),vision:Number(d.get('vision')),elevation:Number(d.get('elevation')),color:String(d.get('color'))});onClose();return;}
    if(mode==='scene' && scene){const environment:TacticalEnvironment={name:String(d.get('name') || ''),biome:String(d.get('biome') || ''),temperature:String(d.get('temperature') || ''),time:String(d.get('time') || ''),notes:String(d.get('notes') || ''),visible:d.getAll('visible').map(String)};void send({type:'updateScene',patch:{name:String(d.get('sceneName')),hexSize:Number(d.get('hexSize')),grid:d.has('grid'),fog:d.has('fog'),environment}}).then(ok=>{if(ok)onClose();});return;}
    if(mode==='token' && token){void send({type:'updateToken',tokenId:token.id,patch:{name:String(d.get('name')),hp:Number(d.get('hp')),maxHp:Number(d.get('maxHp')),initiative:Number(d.get('initiative')),vision:Number(d.get('vision')),elevation:Number(d.get('elevation')),color:String(d.get('color')),ownerId:String(d.get('ownerId') || '') || null}}).then(ok=>{if(ok)onClose();});}
  };
  return <TacticalDialog title={title} onClose={onClose}><form onSubmit={submit} className={styles.formGrid}>
    {mode==='create' && <><label>Nome da cena<input name="name" required maxLength={120} autoFocus placeholder="Nome da operação"/></label><p className={styles.hint}>Criar ou selecionar não troca o mapa dos jogadores. Use Publicar quando estiver pronta.</p></>}
    {mode==='scene' && scene && <><label>Nome da cena<input name="sceneName" required maxLength={120} defaultValue={scene.name}/></label><label>Distância entre centros (px / 1m)<input name="hexSize" type="number" min={10} max={200} required defaultValue={scene.hexSize}/></label><label className={styles.check}><input name="grid" type="checkbox" defaultChecked={scene.grid}/>Exibir grade hexagonal</label><label className={styles.check}><input name="fog" type="checkbox" defaultChecked={scene.fog}/>Névoa de guerra por linha de visão</label><h3>Metadados opcionais da área</h3><p className={styles.hint}>Marque só os campos visíveis aos jogadores; todos podem ficar desmarcados.</p>{Object.entries(ENV_NAMES).map(([key,label])=><div key={key} className={styles.metadataRow}><label>{label}{key==='notes'?<textarea name={key} defaultValue={scene.environment.notes} maxLength={2000}/>:<input name={key} defaultValue={String(scene.environment[key as keyof TacticalEnvironment] || '')} maxLength={300}/>}</label><label className={styles.check}><input name="visible" type="checkbox" value={key} defaultChecked={scene.environment.visible.includes(key)}/>Visível</label></div>)}</>}
    {(mode==='npc' || mode==='token') && <><label>Nome<input name="name" required maxLength={120} defaultValue={token && mode==='token'?token.name:''}/></label>{mode==='npc' && <label>Tipo<select name="kind"><option value="npc">NPC</option><option value="hostile">Hostil</option></select></label>}{(mode==='npc'?[['hp','HP máximo',1],['initiative','Iniciativa',0],['vision','Visão (m)',12],['elevation','Elevação (m)',0]]:[['hp','HP atual',token?.hp],['maxHp','HP máximo',token?.maxHp],['initiative','Iniciativa',token?.initiative],['vision','Visão (m)',token?.vision],['elevation','Elevação (m)',token?.elevation]]).map(([key,label,value])=><label key={String(key)}>{label}<input name={String(key)} type="number" required defaultValue={Number(value)} min={key==='maxHp' || (mode==='npc' && key==='hp')?1:key==='elevation'?-20:key==='initiative'?-100:0} max={key==='hp' || key==='maxHp'?99999:key==='vision'?40:100}/></label>)}<label>Cor<input name="color" type="color" defaultValue={mode==='token'?token?.color:'#ef4444'}/></label>{mode==='token' && <label>ID do dono (vazio = mestre)<input name="ownerId" readOnly={!!token?.characterId} defaultValue={token?.ownerId || ''}/></label>}{mode==='npc' && <p className={styles.hint}>Este compêndio não tem catálogo de criaturas. Os valores são definidos pelo mestre. Modelos manuais duram esta sessão; os tokens posicionados são salvos no servidor.</p>}</>}
    <button type="submit" disabled={!!pending} className={styles.primary}>{mode==='create'?'Criar cena':mode==='npc'?'Criar modelo e posicionar':'Salvar'}</button>
    {mode==='scene' && scene && <button type="button" className={styles.danger} disabled={!!pending} onClick={()=>{if(confirm(`Excluir a cena ${scene.name}?`))void send({type:'deleteScene'}).then(ok=>{if(ok){onClose();selectScene(null);}});}}>Excluir cena</button>}
    {mode==='token' && token && <button type="button" className={styles.danger} disabled={!!pending} onClick={()=>void send({type:'removeToken',tokenId:token.id}).then(ok=>{if(ok){selectToken(null);onClose();}})}>Remover token</button>}
  </form></TacticalDialog>;
}
export function TacticalActionDialog({action,tokenId,initialSlot,onClose}:{action:CharacterAction;tokenId:string|null;initialSlot:ActionKind;onClose:()=>void}) {
  const {view,send,pending}=useTacticalMapStore();const scene=view?.scene,token=scene?.tokens.find(t=>t.id===tokenId);const [slot,setSlot]=React.useState(initialSlot),[formula,setFormula]=React.useState(action.formula || '1d20'),[text,setText]=React.useState(action.name);
  const owns=!!token && (view?.self.role==='admin' || token.ownerId===view?.self.id),turn=owns && (view?.self.role==='admin' || scene?.combat.order[scene.combat.index]===tokenId);
  const lastRoll=[...(scene?.combat.log || [])].reverse().find(l=>l.kind==='roll' && l.tokenId===tokenId);
  return <TacticalDialog title={action.name} onClose={onClose}><p className={styles.actionDescription}>{action.description}</p><form onSubmit={e=>{e.preventDefault();if(tokenId)void send({type:'declareAction',tokenId,kind:slot,text}).then(ok=>{if(ok)onClose();});}}><label>Declaração<textarea value={text} maxLength={500} onChange={e=>setText(e.target.value)}/></label><label>Tipo de ação<select value={slot} onChange={e=>setSlot(e.target.value as ActionKind)}>{(Object.entries(SLOT_NAMES) as [ActionKind,string][]).map(([kind,label])=><option key={kind} value={kind}>{label}</option>)}</select></label><button type="submit" className={styles.primary} disabled={!scene?.combat.active || !tokenId || !turn || !!pending || !scene.combat.actions[tokenId]?.[slot]}>Registrar ação</button>{!scene?.combat.active && <p className={styles.hint}>Declarações de ações ficam disponíveis durante o combate.</p>}<label>Fórmula de dados<input aria-label="Fórmula para rolagem" maxLength={40} value={formula} onChange={e=>setFormula(e.target.value)}/></label><button type="button" disabled={!tokenId || !owns || !!pending} onClick={()=>{if(tokenId)void send({type:'roll',tokenId,formula,label:action.name});}}><Dices size={18}/>Rolar dados no servidor</button>{!tokenId && <p className={styles.hint}>O mestre precisa posicionar o token da ficha para registrar dados.</p>}</form>{lastRoll && <p role="status" className={styles.rollResult}>{lastRoll.text}</p>}</TacticalDialog>;
}
